### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by jiahuanluo** [fpcsong/emotionflow#1]
Thanks for your job!
How to get the [friends_transcript.json](https://github.com/fpcsong/emotionflow/blob/e3e2698822619982ba9275d710d960d131ed9d67/train.py#L481) file in [train.py](https://github.com/fpcsong/emotionflow/blob/e3e2698822619982ba9275d710d960d131ed9d67/train.py)?
Didn't find in [MELD](https://github.com/declare-lab/MELD).

Thanks!

**Comment by fpcsong** [comment]
This file is not used, I forgot to delete it, sorry

**Comment by fpcsong** [comment]
Sorry, I just uploaded this file, but this file is not necessary, it is only used to count the frequency of speakers, you can extract the speakers from train set.
