### ISSUE TITLE
HI~ I have a train.py question

### ISSUE THREAD

**Issue by asas38862002** [fpcsong/emotionflow#3]
I type this command 

python train.py -tr -wp 0 -bsz 1 -acc_step 8 -lr 1e-4 -ptmlr 1e-5 -dpt 0.3 -bert_path roberta-[base, large] -epochs [20, 5]

it replys train.py: error: argument -epochs/--epochs: invalid int value: '[20,'

How to solve the question ? 

Thanks .

**Comment by fpcsong** [comment]
[base, large] means base or large, [20, 5] the same.
run 
`python train.py -tr -wp 0 -bsz 1 -acc_step 8 -lr 1e-4 -ptmlr 1e-5 -dpt 0.3 -bert_path roberta-base -epochs 20`
for base model and 
`python train.py -tr -wp 0 -bsz 1 -acc_step 8 -lr 1e-4 -ptmlr 1e-5 -dpt 0.3 -bert_path roberta-large -epochs 5`
for large model.
